### ISSUE TITLE
CDK Deploy failed with below errors

### ISSUE THREAD

**Issue by jackiecheng2008** [aws-samples/aws-cdk-apigateway-cloudwatch-dashboard#2]
DemoAppApiDashboardStack | 16/47 | 8:31:22 a.m. | CREATE_IN_PROGRESS   | AWS::Lambda::Function   
    | TransactionsApi/GetTransaction (TransactionsApiGetTransactionE0C74A2F)
DemoAppApiDashboardStack | 16/47 | 8:31:23 a.m. | CREATE_FAILED        | AWS::Lambda::Function   
    | TransactionsApi/GetTransaction (TransactionsApiGetTransactionE0C74A2F) GetTransaction already exists in stack arn:aws:cloudformation:us-east-1:668498687758:stack/TransactionsLambdaDashboardStack/599835c0-442c-11ec-8465-1280b4dd1159
        new Function (C:\_Projects\CBSA\Ref\aws-cdk-apigateway-cloudwatch-dashboard\node_modules\@aws-cdk\aws-lambda\lib\function.ts:388:35)
        \_ new TransactionsAPI (C:\_Projects\CBSA\Ref\aws-cdk-apigateway-cloudwatch-dashboard\lib\cdk-transactions-api-lambda-construct.ts:10:39)
        \_ Object.<anonymous> (C:\_Projects\CBSA\Ref\aws-cdk-apigateway-cloudwatch-dashboard\bin\api-dashboard.ts:15:1)
        \_ Module._compile (internal/modules/cjs/loader.js:1063:30)
        \_ Module.m._compile (C:\_Projects\CBSA\Ref\aws-cdk-apigateway-cloudwatch-dashboard\node_modules\ts-node\src\index.ts:1056:23)
        \_ Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
        \_ Object.require.extensions.<computed> [as .ts] (C:\_Projects\CBSA\Ref\aws-cdk-apigateway-cloudwatch-dashboard\node_modules\ts-node\src\index.ts:1059:12)
        \_ Module.load (internal/modules/cjs/loader.js:928:32)
        \_ Function.Module._load (internal/modules/cjs/loader.js:769:14)
        \_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)      
        \_ main (C:\_Projects\CBSA\Ref\aws-cdk-apigateway-cloudwatch-dashboard\node_modules\ts-node\src\bin.ts:198:14)
        \_ Object.<anonymous> (C:\_Projects\CBSA\Ref\aws-cdk-apigateway-cloudwatch-dashboard\node_modules\ts-node\src\bin.ts:288:3)
        \_ Module._compile (internal/modules/cjs/loader.js:1063:30)
        \_ Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
        \_ Module.load (internal/modules/cjs/loader.js:928:32)
        \_ Function.Module._load (internal/modules/cjs/loader.js:769:14)
        \_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)      
        \_ internal/main/run_main_module.js:17:47

**Comment by jackiecheng2008** [comment]
It seems like this project shares some same resources as https://github.com/aws-samples/aws-cdk-lambda-cloudwatch-dashboard ; unfortunately, I just deployed the first stack which is conflicting with the new stack.

**Comment by jackiecheng2008** [comment]
Same issue: there is no usage about how to use the api gateway. It would be very helpful.

**Comment by jackiecheng2008** [comment]
Same issue: after "cdk deploy successfully", no data available in each widget.

**Comment by rjesh-git** [comment]
This example does not include any sample data generation code, widgets will show metrics based on the API gateway usage. Closing this issue!
